'use client'

import { memo, useState } from 'react'
import type { Country } from '@/types/bess'
import { CURRENCY_SYMBOLS, COUNTRY_NAMES } from '@/lib/constants'
import { CO2_GRID_FACTOR } from '@/data/rates'
import InfoTooltip from '@/components/InfoTooltip'

const GRID_EMISSION_FACTOR = CO2_GRID_FACTOR

// Equivalent metrics
function treesEquivalent(co2Kg: number) {
  return Math.round(co2Kg / 21) // ~21 kg CO₂ per tree per year
}

function carsEquivalent(co2Kg: number) {
  return (co2Kg / 4600).toFixed(1) // ~4.6 tonnes per car per year
}

function flightsEquivalent(co2Kg: number) {
  return Math.round(co2Kg / 1100) // ~1.1t CO₂ per KL-LON return
}

interface ESGDashboardProps {
  country: Country
  solarKw: number
  batteryCapacityKwh: number
  annualSolarGenKwh: number // daily × 365
  coveragePct: number // 0-1
  co2AvoidedKg: number
  annualSavingsLocal: number
  systemType: 'residential' | 'commercial' | 'grid'
}

function fmt(n: number, country: Country, digits = 0) {
  return `${CURRENCY_SYMBOLS[country]}${n.toLocaleString('en-US', { maximumFractionDigits: digits, minimumFractionDigits: digits })}`
}

const ESGDashboard = memo(function ESGDashboard(props: ESGDashboardProps) {
  const { country, solarKw, batteryCapacityKwh, annualSolarGenKwh, coveragePct, co2AvoidedKg, annualSavingsLocal, systemType } = props
  const [copied, setCopied] = useState(false)

  const co2Tonnes = co2AvoidedKg / 1000
  const renewableFraction = Math.round(coveragePct * 100)
  const gridDependency = 100 - renewableFraction
  const trees = treesEquivalent(co2AvoidedKg)
  const cars = carsEquivalent(co2AvoidedKg)
  const flights = flightsEquivalent(co2AvoidedKg)

  // 20-year projections
  const co2_20yr = co2Tonnes * 20
  const savings_20yr = annualSavingsLocal * 20

  // CDP/GRI/TCFD formatted snippet
  const reportSnippet = `ESG ENERGY & CLIMATE METRICS
Reporting Period: ${new Date().getFullYear()} (Projected Annual)
Location: ${COUNTRY_NAMES[country]}
System: ${Math.round(solarKw)} kW Solar PV + ${Math.round(batteryCapacityKwh)} kWh Battery Storage (${systemType})
Framework References: GRI 302/305, CDP C6/C7, TCFD Metrics & Targets

SCOPE 2 EMISSIONS REDUCTION
  Grid emission factor: ${GRID_EMISSION_FACTOR[country]} kg CO₂e/kWh (IEA 2024)
  Annual renewable generation: ${Math.round(annualSolarGenKwh).toLocaleString()} kWh
  Annual CO₂ avoided: ${co2Tonnes.toFixed(1)} tonnes CO₂e
  20-year cumulative avoidance: ${co2_20yr.toFixed(0)} tonnes CO₂e

ENERGY MIX
  Renewable fraction: ${renewableFraction}%
  Grid dependency: ${gridDependency}%
  On-site storage capacity: ${Math.round(batteryCapacityKwh)} kWh

FINANCIAL IMPACT
  Annual energy cost reduction: ${fmt(annualSavingsLocal, country, 0)}
  20-year projected savings: ${fmt(savings_20yr, country, 0)}

Generated by battery.mom · ${new Date().toLocaleDateString('en-GB')}`

  const copySnippet = async () => {
    try {
      await navigator.clipboard.writeText(reportSnippet)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch { /* fallback not needed */ }
  }

  return (
    <div className="bg-paper-100 border border-ink/10 rounded-card p-5 mt-8">
      <div className="flex items-center justify-between mb-5">
        <div>
          <h3 className="text-base font-bold text-ink flex items-center gap-2">
            ESG reporting dashboard
            <InfoTooltip content="Ready-to-use metrics for sustainability reporting. Covers GRI 302 (Energy), GRI 305 (Emissions), CDP Climate Change questionnaire sections C6/C7, and TCFD Metrics & Targets pillar. Copy the formatted snippet directly into your ESG report." />
          </h3>
          <p className="text-xs text-ink-500 mt-0.5">Annual projections for CDP, GRI, and TCFD reporting</p>
        </div>
        <div className="flex items-center gap-2">
          <span className="px-2 py-0.5 text-[10px] font-semibold text-blue-700 bg-blue-50 rounded-full">GRI 302/305</span>
          <span className="px-2 py-0.5 text-[10px] font-semibold text-purple-700 bg-purple-50 rounded-full">CDP C6/C7</span>
          <span className="px-2 py-0.5 text-[10px] font-semibold text-amber-700 bg-amber-50 rounded-full">TCFD</span>
        </div>
      </div>

      {/* Key metrics grid */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-5">
        <div className="bg-brand-50 rounded-lg p-3 text-center">
          <div className="text-[10px] text-ink-500 uppercase tracking-wide mb-1">CO₂ avoided</div>
          <div className="text-xl font-bold text-brand-700">{co2Tonnes.toFixed(1)}t</div>
          <div className="text-[10px] text-ink-400">per year</div>
        </div>
        <div className="bg-blue-50 rounded-lg p-3 text-center">
          <div className="text-[10px] text-ink-500 uppercase tracking-wide mb-1">Renewable %</div>
          <div className="text-xl font-bold text-blue-700">{renewableFraction}%</div>
          <div className="text-[10px] text-ink-400">of total energy</div>
        </div>
        <div className="bg-amber-50 rounded-lg p-3 text-center">
          <div className="text-[10px] text-ink-500 uppercase tracking-wide mb-1">Solar gen.</div>
          <div className="text-xl font-bold text-amber-700">{(annualSolarGenKwh / 1000).toFixed(0)}</div>
          <div className="text-[10px] text-ink-400">MWh/year</div>
        </div>
        <div className="bg-paper-200 rounded-lg p-3 text-center">
          <div className="text-[10px] text-ink-500 uppercase tracking-wide mb-1">Grid factor</div>
          <div className="text-xl font-bold text-ink-700">{GRID_EMISSION_FACTOR[country]}</div>
          <div className="text-[10px] text-ink-400">kg CO₂e/kWh</div>
        </div>
      </div>

      {/* Equivalences */}
      <div className="bg-paper-200 rounded-lg p-4 mb-5">
        <div className="text-xs font-semibold text-ink-700 mb-2">Annual impact equivalences</div>
        <div className="grid grid-cols-3 gap-4 text-center">
          <div>
            <div className="text-2xl mb-0.5">🌳</div>
            <div className="text-sm font-bold text-ink-800">{trees.toLocaleString()}</div>
            <div className="text-[10px] text-ink-500">trees planted</div>
          </div>
          <div>
            <div className="text-2xl mb-0.5">🚗</div>
            <div className="text-sm font-bold text-ink-800">{cars}</div>
            <div className="text-[10px] text-ink-500">cars off the road</div>
          </div>
          <div>
            <div className="text-2xl mb-0.5">✈️</div>
            <div className="text-sm font-bold text-ink-800">{flights}</div>
            <div className="text-[10px] text-ink-500">KL↔London flights</div>
          </div>
        </div>
      </div>

      {/* 20-year projection */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-5">
        <div className="bg-brand-50 rounded-lg p-4">
          <div className="text-xs text-ink-500 mb-1">20-Year CO₂ Avoidance</div>
          <div className="text-2xl font-bold text-brand-700">{co2_20yr.toFixed(0)} tonnes</div>
          <div className="text-xs text-ink-500 mt-1">Scope 2 reduction · {COUNTRY_NAMES[country]} grid mix</div>
        </div>
        <div className="bg-blue-50 rounded-lg p-4">
          <div className="text-xs text-ink-500 mb-1">20-Year Energy Savings</div>
          <div className="text-2xl font-bold text-blue-700">{fmt(savings_20yr, country, 0)}</div>
          <div className="text-xs text-ink-500 mt-1">At current tariff rates</div>
        </div>
      </div>

      {/* Copy-ready snippet */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <div className="text-xs font-semibold text-ink-700">Report-ready snippet</div>
          <button
            onClick={copySnippet}
            className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs font-semibold text-brand-700 bg-brand-50 border border-brand-200 rounded-lg hover:bg-brand-100 transition-colors"
          >
            {copied ? (
              <>
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" /></svg>
                Copied!
              </>
            ) : (
              <>
                <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 16H6a2 2 0 01-2-2V6a2 2 0 012-2h8a2 2 0 012 2v2m-6 12h8a2 2 0 002-2v-8a2 2 0 00-2-2h-8a2 2 0 00-2 2v8a2 2 0 002 2z" /></svg>
                Copy for report
              </>
            )}
          </button>
        </div>
        <pre className="bg-ink text-paper-200 text-[11px] p-4 rounded-lg overflow-x-auto leading-relaxed whitespace-pre-wrap">
          {reportSnippet}
        </pre>
      </div>
    </div>
  )
})

export default ESGDashboard
